### ISSUE TITLE
Compatibility with PyTorch CUDA dep version

### ISSUE THREAD

**Issue by zbarry** [tlambert03/pycudadecon#15]
First off, thanks for putting together this really useful package! It's been working really well for me.

I've run into a particular incompatibility with the cudatoolkit versions that `llspylibs` and PyTorch were built against, which you can see given this following example conda environment file:

```yaml
name: test
channels:
  - pytorch
  - conda-forge
  - talley
  - defaults
dependencies:
  - python =3.7
  - numpy
  - pytorch =1.6.0
  - torchvision =0.7.0
  - cudatoolkit =10.1.243
  - cudatoolkit-dev =10.1.243
  - pycudadecon=0.1.2=py37_0
  - llspylibs=0.2.0=cu10.0
```

From what I can tell based on attempted installation via [mamba](https://github.com/mamba-org/mamba/) and this potentially helpful error message:

> Encountered problems while solving.
> Problem: package llspylibs-0.2.0-cu10.0 requires cudatoolkit 10.0.130, but none of the providers can be installed

`llspylibs` is specifically built for `cudatoolkit` `10.0.130`, whereas there are no versions of pytorch either from the `conda-forge` or `pytorch` channels that are built against that particular version. Because of this, I am not able to have both `pycudadecon` and `pytorch` with CUDA support enabled in the same conda environment.

I was wondering if it was possible for me to build `llspylibs` myself, but I'm not sure where that library actually originates from - `LLspy` has its own repo, but references to `llspylibs` in the docs specifically seem to only refer to the binary on the `talley` conda channel. 

Would it be possible for me to build `llspylibs` somehow? Thanks for any guidance you can provide!
